// models/disbursement.server.js
// Records when organization pays landlord their net rent.
// Summarises one or more RentPayments — does NOT replace them.
// RentPayment = what tenant paid. Disbursement = what landlord received.
// NEVER hard delete. Soft delete only (deleted: true).

import { mongoose } from "../config/db.server.js";

const { Schema } = mongoose;

const disbursementSchema = new Schema(
  {
    // ── Organization scope ─────────────────────────────────────────
    organizationId: {
      type: Schema.Types.ObjectId,
      ref: 'Organization',
      required: true,
      index: true,
    },

    // ── Links ─────────────────────────────────────────────────
    landlordId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
      // User with role: landlord
    },
    propertyIds: {
      type: [Schema.Types.ObjectId],
      ref: "Property",
      default: [],
      // properties included in this disbursement
      // a landlord with multiple properties may receive
      // one combined disbursement covering all properties
    },
    rentPaymentIds: {
      type: [Schema.Types.ObjectId],
      ref: "RentPayment",
      default: [],
      // which rent payments are included in this disbursement
      // links disbursement back to source rent payments
    },

    // ── Period ────────────────────────────────────────────────
    periodStart: {
      type: Date,
      required: true,
      // start of period this disbursement covers
      // e.g. 2026-05-01 for May 2026
    },
    periodEnd: {
      type: Date,
      required: true,
      // end of period
      // e.g. 2026-05-31 for May 2026
    },

    // ── Amounts ───────────────────────────────────────────────
    // All amounts stored as Number in pounds to exactly 2dp.
    // Always Math.round(amount * 100) / 100 before save.
    grossRent: {
      type: Number,
      required: true,
      // total rent received from tenants this period
    },
    totalCommission: {
      type: Number,
      required: true,
      // organization commission deducted (copied from RentPayment records)
      // NEVER recalculated from current property settings
    },
    totalVat: {
      type: Number,
      default: 0,
      // VAT on commission if organization is VAT registered
    },
    deductions: {
      type: [
        {
          description: { type: String, required: true },
          // e.g. 'Plumber callout — 14 Victoria Street'
          amount: { type: Number, required: true },
          // positive number — will be deducted from net
          receiptDocumentId: {
            type: Schema.Types.ObjectId,
            ref: "Document",
            default: null,
            // optional receipt/invoice upload
          },
          // _id is auto-generated by Mongoose for array subdocuments
        },
      ],
      default: [],
      // maintenance costs or other deductions from landlord payment
      // e.g. organization paid plumber on landlord's behalf
      // deducted from disbursement amount
    },
    totalDeductions: {
      type: Number,
      default: 0,
      // sum of all deductions array amounts
    },
    netAmount: {
      type: Number,
      required: true,
      // what landlord actually receives:
      // grossRent - totalCommission - totalVat - totalDeductions
      // VALIDATION: must be > 0 before save (enforced in action)
    },

    // ── Payment details ───────────────────────────────────────
    status: {
      type: String,
      enum: [
        "pending",  // calculated but not yet paid
        "paid",     // transferred to landlord
        "on_hold",  // held for a reason (dispute etc)
      ],
      default: "pending",
      index: true,
    },
    paidDate: {
      type: Date,
      default: null,
      // date organization transferred money to landlord
    },
    paymentMethod: {
      type: String,
      enum: ["bacs", "faster_payment", "cheque", "cash", "other", null],
      default: null,
    },
    bankReference: {
      type: String,
      trim: true,
      default: null,
      // bank transfer reference
      // e.g. "PROPLET MAY26 THOMPSON"
    },

    // ── Landlord bank details snapshot at time of disbursement ─
    // Copied from landlord.landlordData.bankDetails at creation time
    // Stored so historical records stay accurate if landlord changes bank
    landlordBankSnapshot: {
      accountName:   { type: String, default: null },
      accountNumber: { type: String, default: null },
      sortCode:      { type: String, default: null },
      bankName:      { type: String, default: null },
    },

    notes: {
      type: String,
      trim: true,
      default: null,
    },

    // ── Audit ─────────────────────────────────────────────────
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    markedPaidBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    // ── Soft delete ───────────────────────────────────────────
    // NEVER hard delete financial records — required for audit trail
    deleted:   { type: Boolean, default: false },
    deletedAt: { type: Date, default: null },
    deletedBy: { type: Schema.Types.ObjectId, ref: "User", default: null },
  },
  { timestamps: true }
);

// ── Indexes ───────────────────────────────────────────────────
disbursementSchema.index({ organizationId: 1, landlordId: 1 });
disbursementSchema.index({ organizationId: 1, status: 1 });
disbursementSchema.index({ organizationId: 1, periodStart: 1 });
disbursementSchema.index({ organizationId: 1, deleted: 1 });
disbursementSchema.index({ organizationId: 1, landlordId: 1, periodStart: 1 });
// check for existing disbursement for same landlord + period

export const Disbursement =
  mongoose.models.Disbursement ||
  mongoose.model("Disbursement", disbursementSchema);
