// models/MaintenanceJob.server.js
// Core maintenance job record. Tracks repair and maintenance requests
// from report through to completion.
// Language rule: "job", "works order", "record" -- never "compliance".

import { mongoose } from "../config/db.server.js";

const { Schema } = mongoose;

const maintenanceJobSchema = new Schema(
  {
    // ── Agency scope ─────────────────────────────────────────
    agencyId: {
      type: Schema.Types.ObjectId,
      ref: "Agency",
      required: true,
      index: true,
    },

    // ── Job reference ─────────────────────────────────────────
    jobRef: {
      type: String,
      required: true,
      // Auto-generated: MJ-2026-0001
      // Sequential per agency. Never set manually.
      // See: utils/maintenance.server.js → generateJobRef()
    },

    // ── Entity links ──────────────────────────────────────────
    propertyId: {
      type: Schema.Types.ObjectId,
      ref: "Property",
      required: true,
      index: true,
    },
    tenancyId: {
      type: Schema.Types.ObjectId,
      ref: "Tenancy",
      default: null,
      // Linked if property is currently tenanted at time of reporting
    },
    landlordId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
      // Denormalised from property for query efficiency
    },
    contractorId: {
      type: Schema.Types.ObjectId,
      ref: "Contractor",
      default: null,
      // Optional at all stages — small agencies use handymen not in system
    },

    // ── Job details ───────────────────────────────────────────
    category: {
      type: String,
      enum: [
        "plumbing",
        "electrical",
        "gas",
        "heating",
        "roofing",
        "structural",
        "damp_mould",    // Awaab's Law — auto-flagged, investigated within 14 days
        "pest_control",
        "doors_windows",
        "flooring",
        "decorating",
        "garden",
        "appliances",
        "cleaning",
        "inspection",
        "other",
      ],
      required: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxLength: 200,
      // Short description: "Boiler not heating water"
    },
    description: {
      type: String,
      trim: true,
      default: null,
      maxLength: 2000,
    },
    location: {
      type: String,
      trim: true,
      default: null,
      // Where in the property: "Kitchen", "Main bathroom"
    },

    // ── Priority ──────────────────────────────────────────────
    priority: {
      type: String,
      enum: ["emergency", "urgent", "routine", "planned"],
      default: "routine",
      index: true,
      // emergency: gas leak, flooding, no heating in winter — action within 24 hours
      // urgent:    boiler failure, no hot water — action within 3-5 days
      // routine:   dripping tap, broken shelf — action within 28 days
      // planned:   scheduled maintenance, inspections — action on scheduled date
    },

    // ── Source of report ──────────────────────────────────────
    reportedBy: {
      type: String,
      enum: ["tenant", "landlord", "agent", "inspection", "system"],
      default: "agent",
      // system = auto-generated by planned maintenance schedule
    },
    reportedByUserId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
      // If reported by a known user in the system
    },
    reportedDate: {
      type: Date,
      required: true,
      default: Date.now,
    },

    // ── Status ────────────────────────────────────────────────
    status: {
      type: String,
      enum: [
        "reported",            // Just logged, not yet actioned
        "landlord_approval",   // Waiting for landlord to approve works
        "approved",            // Landlord approved works
        "contractor_assigned", // Contractor instructed
        "in_progress",         // Works underway
        "completed",           // Works done, pending confirmation
        "closed",              // Fully closed, invoiced
        "cancelled",           // Cancelled for any reason
        "on_hold",             // Temporarily paused
      ],
      default: "reported",
      index: true,
    },

    // ── Landlord approval ─────────────────────────────────────
    requiresLandlordApproval: {
      type: Boolean,
      default: false,
      // Auto-set to true if estimatedCost > agency threshold (default £500)
    },
    landlordApprovalStatus: {
      type: String,
      enum: ["pending", "approved", "declined", null],
      default: null,
    },
    landlordApprovalDate:  { type: Date, default: null },
    landlordApprovalNotes: { type: String, trim: true, default: null },

    // ── Dates ─────────────────────────────────────────────────
    targetDate: {
      type: Date,
      default: null,
      // Target completion date. Auto-suggested from priority:
      //   emergency: reportedDate + 1 day
      //   urgent:    reportedDate + 5 days
      //   routine:   reportedDate + 28 days
      //   planned:   scheduledDate from planned schedule
    },
    scheduledDate: {
      type: Date,
      default: null,
      // Date contractor is scheduled to attend
    },
    completedDate: {
      type: Date,
      default: null,
    },
    closedDate: {
      type: Date,
      default: null,
    },

    // ── Cost ──────────────────────────────────────────────────
    estimatedCost: {
      type: Number,
      default: null,
      // Estimated cost in pounds
    },
    actualCost: {
      type: Number,
      default: null,
      // Actual cost once completed
    },
    invoiceReference: {
      type: String,
      trim: true,
      default: null,
      // Contractor invoice number
    },
    costResponsibility: {
      type: String,
      enum: ["landlord", "tenant", "agency", "insurance", "tbc"],
      default: "landlord",
    },
    agencyExpenseId: {
      type: Schema.Types.ObjectId,
      ref: "AgencyExpense",
      default: null,
      // If agency paid contractor: link to AgencyExpense record
      // Creates the audit trail for landlord deductions
    },

    // ── Planned maintenance link ──────────────────────────────
    isPlannedMaintenance: {
      type: Boolean,
      default: false,
    },
    plannedScheduleId: {
      type: Schema.Types.ObjectId,
      ref: "PlannedMaintenanceSchedule",
      default: null,
    },

    // ── Awaab's Law ───────────────────────────────────────────
    isAwaabsLaw: {
      type: Boolean,
      default: false,
      // Auto-set when category === 'damp_mould'
      // Damp and mould must be investigated within 14 days
      // Never manually toggled off once set
    },
    awaabsLawInvestigationDeadline: {
      type: Date,
      default: null,
      // Auto-set: reportedDate + 14 days when isAwaabsLaw = true
    },

    // ── Notes ─────────────────────────────────────────────────
    notes: {
      type: String,
      trim: true,
      default: null,
      // Inline job notes field
      // Detailed activity log uses generic Note model (entityType: 'maintenance_job')
    },

    // ── Audit ─────────────────────────────────────────────────
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    updatedBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    // ── Soft delete ───────────────────────────────────────────
    deleted:   { type: Boolean, default: false },
    deletedAt: { type: Date, default: null },
    deletedBy: { type: Schema.Types.ObjectId, default: null },
  },
  { timestamps: true }
);

// ── Indexes ───────────────────────────────────────────────────
maintenanceJobSchema.index({ agencyId: 1, status: 1 });
maintenanceJobSchema.index({ agencyId: 1, propertyId: 1 });
maintenanceJobSchema.index({ agencyId: 1, priority: 1 });
maintenanceJobSchema.index({ agencyId: 1, category: 1 });
maintenanceJobSchema.index({ agencyId: 1, contractorId: 1 });
maintenanceJobSchema.index({ agencyId: 1, targetDate: 1 });
maintenanceJobSchema.index({ agencyId: 1, isAwaabsLaw: 1 });
maintenanceJobSchema.index({ agencyId: 1, deleted: 1 });
maintenanceJobSchema.index({ agencyId: 1, jobRef: 1 }, { unique: true });

export const MaintenanceJob =
  mongoose.models.MaintenanceJob ||
  mongoose.model("MaintenanceJob", maintenanceJobSchema);
